# Generated by Django 3.2.22 on 2023-10-31 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(default=2000)),
                ('link', models.CharField(max_length=500)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kara.theme')),
            ],
        ),
    ]
